version: '3.2'

services:
    web:
        build:
            context: ./docker/web
        ports:
            - '${WEB_PORT:-8020}:80'
        volumes:
            - ./webroot:/var/www/html
            - ./data:/data
        environment:
            - XDEBUG_MODE=trace,debug,coverage
            - SQLITE_DB_PATH=/data/weather.db
            - DB_NAME=${DB_NAME:-m450}
            - OPENWEATHER_KEY=${OPENWEATHER_KEY}

